### ISSUE TITLE
Use option pattern to configure function blocks

### ISSUE THREAD

**Issue by siredmar** [ci4rail/io4edge-client-go#20]
To cleanup the configuration it might make sense to use the option pattern.
https://www.sohamkamani.com/golang/options-pattern/

Example usage: 
- UploadConfiguration(WithOutputFrittingMask(..), WithOutputWatchdogTimeout(..)) // setting two values explicitly, others default
- UploadConfiguration(WithOutputFrittingMask(..), OutputWatchdogMask(..)) // setting two values explicitly, others default
- OutputWatchdogMask(WithOutputWatchdogTimeout(..) // setting only one value explicitly, others default
- WithOutputWatchdogTimeout() // all values default

https://github.com/ci4rail/io4edge-client-go/blob/a0a653b0d9c2d1aa0b8224ec5278b0204d9dbf76/binaryiotypea/client.go#L68

**Comment by KlausPopp** [comment]
Great idea!

**Comment by KlausPopp** [comment]
@siredmar: Like this: https://github.com/ci4rail/io4edge-client-go/blob/functional_option_pattern/binaryiotypea/client.go?

**Comment by siredmar** [comment]
@popples lgtm

**Comment by siredmar** [comment]
@popples However, i would use `Configuration` instead of `fspb.ConfigurationSet` as parameter and hide the pb type.

**Comment by siredmar** [comment]
you are right. never mind

**Comment by KlausPopp** [comment]
Fixed with _7acf976dfb301d7911a492864dac65c4f05ee0fe_
